### ISSUE TITLE
Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected persists on display.

### ISSUE THREAD

**Issue by LaxmiNarasimhaMurthy** [LaxmiNarasimhaMurthy/VMCS#1]
After collecting Cash when the maintainer pushes “Press Here When Finished” the simulation does not clear the values on the completion of a maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected persists on display.

**Comment by LaxmiNarasimhaMurthy** [comment]
Please note that a branch "VMCS_DEF_#1" is created. Please use the same

**Comment by ankesh12** [comment]
Accepted the issue. Doing the impact analysis. Will proceed with the bug fix upon analysis.

**Comment by ankesh12** [comment]
Bug fixed. Forwarding to QA team to test and verify.

**Comment by ankesh12** [comment]
Merged with Master. Transfering to QA for integration testing.

**Comment by sambhavk11** [comment]
Sending to user rep for verification of  changes made  and obtaining  approval for the release.

**Comment by sounderya** [comment]
Verified the bug fixes. Everything looks good.
Approved for release.

**Comment by LaxmiNarasimhaMurthy** [comment]
Rolling out the release RC1.0.9 to production.

**Comment by LaxmiNarasimhaMurthy** [comment]
Issue closed
