### ISSUE TITLE
The System is required to display the cash amount available by denomination at a glance. 

### ISSUE THREAD

**Issue by LaxmiNarasimhaMurthy** [LaxmiNarasimhaMurthy/VMCS#2]
Using the current version of the system, the Maintainer has to manually calculate the amounts collected which is frustrating. The System is required to display the cash amount available by denomination at a glance.

**Comment by LaxmiNarasimhaMurthy** [comment]
Please note that a branch "VMCS_ENH_#1" is created. Please use the same

**Comment by sambhavk11** [comment]
Accpeted the issue . Working on it .

**Comment by sambhavk11** [comment]
After doing the impact analysis ,implemented the changes as suggested. Forwarding it to QA to verify

**Comment by ankesh12** [comment]
Accepting. Conducting integration Test and Document Review.

**Comment by sambhavk11** [comment]
Merged with master .Transferring to QA for testing

**Comment by ankesh12** [comment]
Tested on the pre-release RC1.0.9.
Completed Integration testing. Everything looks fine.
Document reviewed and looks fine.
Approved for release.

**Comment by ankesh12** [comment]
Sending to user rep for verifying changes and providing approval for release.

**Comment by sounderya** [comment]
Verified the enhancements. Everything looks good.
Approved for release.

**Comment by sounderya** [comment]
Transferring to dev team for rolling out to production.

**Comment by LaxmiNarasimhaMurthy** [comment]
Rolling out the release RC1.0.9 to production.
